apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: psp-role
  namespace: blue
rules:
  - apiGroups:
      - ""
    resources:
      - podsecuritypolicy
    resourceNames:
      - restrict-root
    verbs: ["use","list","get"]
